### ISSUE TITLE
support for libgpiod?

### ISSUE THREAD

**Issue by dkebler** [fivdi/onoff#151] opened 2019-06-11 18:48 UTC
from what I've seen sysfs has been deprecated for libgpiod.   Anything in the works to support it like at the next major version?

https://blog.adafruit.com/2018/11/26/sysfs-is-dead-long-live-libgpiod-libgpiod-for-linux-circuitpython/

**Comment by fivdi** [comment] 2019-06-11 18:55
Duplicate of #118

**Closed** 2019-06-12 19:02 UTC
Labels: question
