### ISSUE TITLE
Restart onoff application - 

### ISSUE THREAD

**Issue by neophob** [fivdi/onoff#55] opened 2016-09-07 14:05 UTC
If I start my ARM machine (note: GPIO 239 is NOT exported yet), start node REPL and enter this code:

```
const GpioOnOff = require('onoff').Gpio;
const button = new GpioOnOff(239, 'in', 'both');
button.watch(function(err, value) {
  console.log('jo');
  console.log(err, value);
});
```

everything works as expected. Now if I close the Node REPL and restart Node REPL (note: GPIO 239 is now exported due the first run on `onoff`) and use the same code as above, the example code does not work anymore. When I `cat` the GPIO `value` I can see that the value change if I press the button. 

When I unexport the GPIO port manually and restart the Node REPL and run the code above, it works again. So it looks like `onoff` has some issues when the GPIO pin already is exported.

Possible options to fix this issue:
- `unexportAlways` option: if `onoff` is started with this option, it will try to unexport the GPIO pin first
- fix the actual issue, might be hard due alot of different systems

Can you reproduce this issue?

**Comment by fivdi** [comment] 2016-09-10 21:56
> Can you reproduce this issue?

I can't reproduce the error on a Raspberry Pi 2.

How is the REPL closed? By hitting `ctrl-c` twice?

Does it work if the following code is run from the REPL directly before the REPL is closed?

```
button.unexport();
```

**Comment by fivdi** [comment] 2016-09-17 19:27
@neophob was it possible to make any progress here?

**Comment by neophob** [comment] 2016-09-18 13:28
im traveling, hope to update this ticket next week

**Comment by fivdi** [comment] 2016-11-14 18:49
@neophob is this still an issue?

**Comment by fivdi** [comment] 2016-12-23 12:50
This issue can't be reproduced on a CHIP computer either. The onoff constructor is implemented to deal with scenarios where a GPIO is already exported before it's used by onoff. It also has an unexport method for explicit cleanup. I'm going to close this issue. If it turns out to be a problem with onoff the issue can be reopened.

**Closed by fivdi** 2016-12-23 12:50 UTC
